language: node_js

node_js:
- '8'

install:
- yarn

script:
- yarn build

before_deploy:
- cd dist/
- zip -r responsive-filemanager *

deploy:
  provider: releases
  api_key:
    secure: uBwwUzR/jZorK0INlV1ITkVa2Oys2SC43KkND4JA/yx4vU0I55dLy0cybZ3/W5CiNciqUojrH5O0d3RdfyAWmEGni9G09+H8w4xxW7BzZ82ntusA71AB7cJ/BmWXknbC0mrEiUKDXJROY158j5jx2SAZJqvKGvL53hwbjnonG6LM8GyrJipbMTKzb4wVkrQj5YbzBJAdDDRAMNvwdrL5hC0nuBtc1hUJasi9Mt7Ir3VSKcjcRXy1iSsE3vDPJrE59HaQPuYAG55YNmdZr+j72JZAh/QGbGCf1HxL6CSmDtKWxZqyWV3aimJNgVAxm5mRRsM2rweBT1HdiqgCasNL9x7t8NnXm8SkZqt+LEYc3d0Yz+HgZjfCWLypJy7p+NSCGW6Qinmi+hdoCEey/pV6HwV4cAcDMpkpqifdlqsF2iCwvhO25QGmS0Wh2dmK4V3g+uDFKWFcBwYWjreEeERKNybySU0PVyCQwWS5lQERYKRv39F9d/x3ardDdsyuGpChcJI//VzTZdMJraKsCEWWJMB+Uevm1y/ATwU5EB0ublgvY+iZyhw1oBEk0+jW216SOeZHV6n5K6v6TlQye64JiD3WV8ewQ1ln9iT6GdNx6EiF5RM1HKWyIq/ENbiAws4VH2EBvIrydw27k1R43IpE4b2ruWU4frRJdbwxrVuxFJ0=
  file: responsive-filemanager.zip
  on:
    tags: true
